// Regenerates src/fonts.js: embeds the OFL fonts in assets/fonts as base64 so
// the film works from file:// with no network access and no server.
//   node tools/embed-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fonts = [
  ['Shrikhand', 'shrikhand-latin-400-normal.woff2'],
  ['Caveat Brush', 'caveat-brush-latin-400-normal.woff2'],
  ['Patrick Hand', 'patrick-hand-latin-400-normal.woff2'],
  ['Titan One', 'titan-one-latin-400-normal.woff2'],
  ['Abril Fatface', 'abril-fatface-latin-400-normal.woff2'],
  ['Alfa Slab One', 'alfa-slab-one-latin-400-normal.woff2'],
  ['Bowlby One SC', 'bowlby-one-sc-latin-400-normal.woff2'],
];
const entries = fonts.map(([family, file]) => {
  const b64 = readFileSync(join(root, 'assets/fonts', file)).toString('base64');
  return `    [${JSON.stringify(family)}, ${JSON.stringify(b64)}]`;
});
const out = `/* GENERATED by tools/embed-fonts.mjs — do not edit by hand.
 * SIL Open Font License 1.1 fonts (see assets/fonts/OFL-LICENSE.txt),
 * embedded so the page runs offline and from file://. */
(function (root) {
  const LR = (root.LR = root.LR || {});
  const FONTS = [
${entries.join(',\n')}
  ];
  function b64ToBuf(b64) {
    const bin = atob(b64);
    const buf = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
    return buf.buffer;
  }
  LR.loadFonts = async function () {
    await Promise.all(FONTS.map(async ([family, b64]) => {
      const face = new FontFace(family, b64ToBuf(b64));
      await face.load();
      document.fonts.add(face);
    }));
  };
})(typeof self !== 'undefined' ? self : globalThis);
`;
writeFileSync(join(root, 'src/fonts.js'), out);
console.log('wrote src/fonts.js', (out.length / 1024).toFixed(0) + 'KB');
